# Generated by Django 5.1.3 on 2024-11-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zproduct', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usersInfos',
        ),
    ]
