# Generated by Django 5.1.3 on 2024-11-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zproduct', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='verificationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('verCode', models.CharField(max_length=6)),
            ],
        ),
    ]
